import React from "react";

const sections = [
  {
    title: "General Terms",
    content: [
      "By accessing and placing an order with Swankk, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Swankk.",
      "Under no circumstances shall Swankk team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Swankk team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.",
      "Swankk will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.",
    ],
  },
  {
    title: "License",
    content: [
      "Swankk grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.",
      'These Terms & Conditions are a contract between you and Swankk (referred to in these Terms & Conditions as "Swankk", "us", "we" or "our"), the provider of the Swankk website and the services accessible from the Swankk website (which are collectively referred to in these Terms & Conditions as the "Swankk Service").',
      'You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Swankk Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.',
    ],
  },
  {
    title: "Definitions and key terms",
    content: [
      "To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:",
    ],
    list: [
      "Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.",
      'Company: when this policy mentions "Company," "we," "us," or "our," it refers to Swankk, that is responsible for your information under this Terms & Conditions.',
      "Country: where Swankk or the owners/founders of Swankk are based, in this case Israel.",
      "Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Swankk and use the services.",
      "Service: refers to the service provided by Swankk as described in the relative terms (if available) and on this platform.",
      "Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",
      "Website: Swankk's site, which can be accessed via this URL: https://swankk.io",
      "You: a person or entity that is registered with Swankk to use the Services.",
    ],
  },
  {
    title: "Restrictions",
    content: ["You agree not to, and you will not permit others to:"],
    list: [
      "License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.",
      "Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.",
      "Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Swankk or its affiliates, partners, suppliers or the licensors of the website.",
    ],
  },
  {
    title: "Return and Refund Policy",
    content: [
      "Thanks for shopping at Swankk. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you're exploring, evaluating, and purchasing our products.",
      "As with any shopping experience, there are terms and conditions that apply to transactions at Swankk. We'll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Swankk, you agree to the terms along with Swankk's Privacy Policy.",
      "If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.",
    ],
  },
  {
    title: "Your Suggestions",
    content: [
      'Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Swankk with respect to the website shall remain the sole and exclusive property of Swankk.',
      "Swankk shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.",
    ],
  },
  {
    title: "Your Consent",
    content: [
      "We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.",
    ],
  },
  {
    title: "Links to Other Websites",
    content: [
      "This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by Swankk. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website's own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.",
    ],
  },
  {
    title: "Cookies",
    content: [
      'Swankk uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.',
    ],
  },
  {
    title: "Changes To Our Terms & Conditions",
    content: [
      "You acknowledge and agree that Swankk may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Swankk when you stop using the Service. You acknowledge and agree that if Swankk disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.",
      "If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.",
    ],
  },
  {
    title: "Modifications to Our website",
    content: [
      "Swankk reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to which it connects, with or without notice and without liability to you.",
    ],
  },
  {
    title: "Updates to Our website",
    content: [
      "Swankk may from time to time provide enhancements or improvements to the features/functionality of the website, which may include patches, bug fixes, updates, upgrades and other modifications.",
      "Updates may modify or delete certain features and/or functionalities of the website. You agree that Swankk has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website to you.",
      "You further agree that all Updates will be (i) deemed to constitute an integral part of the website, and (ii) subject to the terms and conditions of this Agreement.",
    ],
  },
  {
    title: "Third-Party Services",
    content: [
      'We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services").',
      "You acknowledge and agree that Swankk shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Swankk does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.",
      "Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.",
    ],
  },
  {
    title: "Term and Termination",
    content: [
      "This Agreement shall remain in effect until terminated by you or Swankk.",
      "Swankk may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.",
      "This Agreement will terminate immediately, without prior notice from Swankk, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website and all copies thereof from your computer.",
      "Upon termination of this Agreement, you shall cease all use of the website and delete all copies of the website from your computer.",
      "Termination of this Agreement will not limit any of Swankk's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.",
    ],
  },
  {
    title: "Copyright Infringement Notice",
    content: [
      "If you are a copyright owner or such owner's agent and believe any material on our website constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.",
    ],
  },
  {
    title: "Indemnification",
    content: [
      "You agree to indemnify and hold Swankk and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.",
    ],
  },
  {
    title: "No Warranties",
    content: [
      'The website is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Swankk, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Swankk provides no warranty or undertaking, and makes no representation of any kind that the website will meet your requirements, achieve any intended results, be compatible or work with any other software, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.',
      "Without limiting the foregoing, neither Swankk nor any Swankk's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website, or the information, content, and materials or products included thereon; (ii) that the website will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website; or (iv) that the website, its servers, the content, or e-mails sent from or on behalf of Swankk are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.",
      "Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.",
    ],
  },
  {
    title: "Limitation of Liability",
    content: [
      "Notwithstanding any damages that you might incur, the entire liability of Swankk and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website.",
      "To the maximum extent permitted by applicable law, in no event shall Swankk or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website, third-party software and/or third-party hardware used with the website, or otherwise in connection with any provision of this Agreement), even if Swankk or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.",
      "Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.",
    ],
  },
  {
    title: "Severability",
    content: [
      "If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.",
      "This Agreement, together with the Privacy Policy and any other legal notices published by Swankk on the Services, shall constitute the entire agreement between you and Swankk concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Swankk's failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND Swankk AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.",
    ],
  },
  {
    title: "Waiver",
    content: [
      "Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.",
      "No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.",
    ],
  },
  {
    title: "Amendments to this Agreement",
    content: [
      "Swankk reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.",
      "By continuing to access or use our website after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Swankk.",
    ],
  },
  {
    title: "Entire Agreement",
    content: [
      "The Agreement constitutes the entire agreement between you and Swankk regarding your use of the website and supersedes all prior and contemporaneous written or oral agreements between you and Swankk.",
      "You may be subject to additional terms and conditions that apply when you use or purchase other Swankk's services, which Swankk will provide to you at the time of such use or purchase.",
    ],
  },
  {
    title: "Updates to Our Terms",
    content: [
      "We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.",
    ],
  },
  {
    title: "Intellectual Property",
    content: [
      "The website and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by Swankk, its licensors or other providers of such material and are protected by international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of Swankk, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.",
    ],
  },
  {
    title: "Governing Law",
    content: [
      "This Agreement and any dispute or claim arising out of or in connection with it or its subject matter or formation (including non-contractual disputes or claims) shall be governed by and construed exclusively in accordance with the laws of the State of Israel, without giving effect to any principles of conflicts of law.",
      "BY USING THE SERVICE, YOU IRREVOCABLY CONSENT TO THE EXCLUSIVE PERSONAL JURISDICTION OF, AND VENUE IN, THE COMPETENT COURTS LOCATED IN TEL AVIV, ISRAEL FOR ANY DISPUTE ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE SERVICE. YOU HEREBY WAIVE ANY OBJECTION TO SUCH JURISDICTION AND VENUE, INCLUDING ANY CLAIM THAT SUCH COURT IS AN INCONVENIENT OR IMPROPER FORUM.",
      "Any judgment rendered by such courts may be enforced in any court of competent jurisdiction worldwide. If you initiate legal proceedings against Swankk in any jurisdiction other than Tel Aviv, Israel, you agree that Swankk shall be entitled to seek immediate dismissal of such proceedings on jurisdictional grounds, and you shall be liable for all costs and attorneys' fees incurred by Swankk in obtaining such dismissal.",
    ],
  },
  {
    title: "Agreement to Arbitrate",
    content: [
      "PLEASE READ THIS SECTION CAREFULLY — IT AFFECTS YOUR LEGAL RIGHTS. This section applies to any dispute except disputes relating to claims for injunctive or equitable relief regarding the enforcement or validity of Swankk's intellectual property rights. The term \"dispute\" means any dispute, action, or other controversy between you and Swankk concerning the Services or this Agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. \"Dispute\" will be given the broadest possible meaning allowable under law.",
      "BY AGREEING TO THESE TERMS, YOU ARE WAIVING YOUR RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION. You agree that all disputes shall be resolved solely on an individual basis and not in a class, consolidated, or representative action. No arbitration or proceeding shall be combined with another without the prior written consent of all parties to all affected arbitrations or proceedings.",
    ],
  },
  {
    title: "Notice of Dispute",
    content: [
      "In the event of a dispute, you or Swankk must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to: hello@swankk.io. Swankk will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and Swankk will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or Swankk may commence arbitration.",
      "Failure to provide proper notice is a jurisdictional defect. Any action filed without first completing the notice and negotiation process described above shall be dismissed without prejudice.",
    ],
  },
  {
    title: "Binding Arbitration",
    content: [
      "If you and Swankk do not resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration seated in Tel Aviv, Israel. The arbitration shall be conducted in the English or Hebrew language before a single arbitrator, in accordance with the Israeli Arbitration Law, 5728-1968, and the arbitration rules of the Israeli Institute of Commercial Arbitration (IICA), which rules are deemed to be incorporated by reference into this clause.",
      "YOU ARE GIVING UP THE RIGHT TO LITIGATE (OR PARTICIPATE AS A PARTY OR CLASS MEMBER) ALL DISPUTES IN COURT BEFORE A JUDGE OR JURY. The arbitrator's decision shall be final and binding and may be entered as a judgment in any court of competent jurisdiction. Either party may seek interim or preliminary injunctive relief exclusively from the competent courts of Tel Aviv, Israel, as necessary to protect that party's rights or property pending the completion of arbitration.",
      "The costs of arbitration, including arbitrator fees, shall be borne equally by both parties, unless the arbitrator determines that a party has acted in bad faith, in which case the arbitrator may require that party to bear all costs. Each party shall bear its own attorneys' fees unless the arbitrator determines that a claim was frivolous or brought in bad faith, in which case the arbitrator may award attorneys' fees to the prevailing party.",
    ],
  },
  {
    title: "Forum Selection and Waiver of Objection",
    content: [
      "You expressly agree that exclusive jurisdiction for any dispute with Swankk, or in any way relating to your use of the Swankk Service, resides in the courts of Tel Aviv, Israel, and you further agree and expressly consent to the exercise of personal jurisdiction in the courts of Tel Aviv, Israel in connection with any such dispute.",
      "You irrevocably waive, to the fullest extent permitted by law: (a) any objection which you may have at any time to the laying of venue of any proceedings brought in any such court; (b) any claim that any such proceedings brought in such a court have been brought in an inconvenient forum; and (c) any right to object, on the basis that any legal proceedings have been brought in an inappropriate or improper forum, to any proceedings commenced in the courts of Tel Aviv, Israel in respect of this Agreement.",
      "If you attempt to bring any claim, action, or proceeding against Swankk in any forum other than the courts of Tel Aviv, Israel or through arbitration as described herein, you agree to indemnify Swankk for all costs, including reasonable attorneys' fees, incurred in transferring, staying, or dismissing such proceedings.",
    ],
  },
  {
    title: "Submissions and Privacy",
    content: [
      "In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of Swankk without any compensation or credit to you whatsoever. Swankk and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.",
    ],
  },
  {
    title: "Promotions",
    content: [
      'Swankk may, from time to time, include contests, promotions, sweepstakes, or other activities ("Promotions") that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.',
      "Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.",
    ],
  },
  {
    title: "Typographical Errors",
    content: [
      "In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.",
    ],
  },
  {
    title: "Miscellaneous",
    content: [
      "If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of Swankk. Swankk will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. Swankk is an Israeli company incorporated under the laws of the State of Israel, and operates and controls the Swankk Service from its offices in Tel Aviv, Israel. This Agreement shall be governed by and construed exclusively in accordance with the laws of the State of Israel. Any disputes arising under or in connection with this Agreement shall be subject to the sole and exclusive jurisdiction of the competent courts of Tel Aviv, Israel, and you irrevocably submit to such jurisdiction. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Swankk Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms & Conditions (which include and incorporate the Swankk Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and Swankk concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.",
    ],
  },
  {
    title: "Disclaimer",
    content: [
      "Swankk is not responsible for any content, code or any other imprecision.",
      "Swankk does not provide warranties or guarantees.",
      "In no event shall Swankk be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.",
      'The Swankk Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Swankk is a distributor and not a publisher of the content supplied by third parties; as such, Swankk exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Swankk Service. Without limiting the foregoing, Swankk specifically disclaims all warranties and representations in any content transmitted on or in connection with the Swankk Service or on sites that may appear as links on the Swankk Service, or in the products provided as a part of, or otherwise in connection with, the Swankk Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Swankk or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Swankk does not warrant that the Swankk Service will be uninterrupted, uncorrupted, timely, or error-free.',
    ],
  },
  {
    title: "Contact Us",
    content: ["Don't hesitate to contact us if you have any questions."],
    contact: "hello@swankk.io",
  },
];

export default function TermsAndConditions() {
  return (
    <div className="min-h-[60vh] px-5 md:px-8 pt-8 pb-20">
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <h1 className="font-serif text-4xl md:text-5xl font-medium text-black mb-2">
            Terms & Conditions
          </h1>
          <p className="text-sm text-gray-400">Updated at 2026-04-11</p>
        </div>

        <div className="space-y-10">
          {sections.map((section) => (
            <div key={section.title}>
              <p className="text-xs tracking-[0.2em] uppercase text-gray-400 font-medium mb-3">
                {section.title}
              </p>
              <div className="space-y-3">
                {section.content.map((para, i) => (
                  <p key={i} className="text-sm text-gray-700 leading-relaxed">
                    {para}
                  </p>
                ))}
                {section.list && (
                  <ul className="space-y-2 pl-4">
                    {section.list.map((item, i) => (
                      <li key={i} className="text-sm text-gray-700 leading-relaxed list-disc">
                        {item}
                      </li>
                    ))}
                  </ul>
                )}
                {section.contact && (
                  <p className="text-sm text-gray-700">
                    Via Email:{" "}
                    <a
                      href={`mailto:${section.contact}`}
                      className="text-black underline underline-offset-2 hover:text-gray-600 transition-colors"
                    >
                      {section.contact}
                    </a>
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
